### ISSUE TITLE
Namespace should be a module, not class

### ISSUE THREAD

**Issue by DanRathbun** [danawoodman/sketchup-vistools#2]
The namespace class wrapping the uitilities should be a Module, not Class.

For each one of the toolbar / menu `UI::Command` instance objects, you are instantiating a new separate instance of the `SU_Utils` class.

This plugin is a **Library**, of which only _one_ is ever needed. Whenever this is true, the class wrapper should be Module, not Class. (A Class is something we need to make many of.)

**Comment by danawoodman** [comment]
Thanks for pointing that out, I hadn't revised to code in a while. Fixed!
