### ISSUE TITLE
SketchupExtension registration script - wrong info

### ISSUE THREAD

**Issue by DanRathbun** [danawoodman/sketchup-vistools#4]
The SketchupExtension registration script SU_Utils.rb, has the wrong info.

The info is for SU_MaterialChanger (looks the 'ol "cut-n-paste" boo-boo.)

**Comment by DanRathbun** [comment]
ALSO... Extension name is mispelled:

```
"Utilies"
```

**Comment by danawoodman** [comment]
Thank you for reporting that Dan. Ooops! Fixed!
